### ISSUE TITLE
release tag?

### ISSUE THREAD

**Issue by fossfreedom** [zalesyc/budgie-media-player-applet#3]
Hi,

 congrats on your budgie plugin.  Nicely done!

Will you be creating a git release and tag?

for ubuntu budgie we would like to package your work as a debian package and make it available to all supported budgie users on ubuntu.

cheers.

**Comment by zalesyc** [comment]
Hi,

I'm glad you like my Budgie applet.

I've just created the Git release and tag for this project. 

Cheers

**Comment by fossfreedom** [comment]
Many thanks.  Will let you know when it's done and made available to install.

Cheers for all of your hard work.

**Comment by fossfreedom** [comment]
@zalesyc FYI https://discourse.ubuntubudgie.org/t/24-04-testing-are-you-brave-enough/6928/55?u=fossfreedom   many thanks again.
